import { SyntaxConstants } from "./types";

export const LINE_TERMINATORS = ["", "\n", "\r\n"];

export const EXTENSION_TO_LANGUAGE = {
    asm: "Assembly",
    c: "C",
    h: "C",
    cpp: "C++",
    hpp: "C++",
    tpp: "C++",
    ipp: "C++",
    cc: "C++",
    hh: "C++",
    C: "C++",
    H: "C++",
    cxx: "C++",
    hxx: "C++",
    "c++": "C++",
    "h++": "C++",
    go: "Go",
    Makefile: "Makefile",
    py: "Python",
    sh: "Shell",
    tex: "LaTeX",
    java: "Java",
    cs: "C#",
    m: "ObjectiveC",
    rs: "Rust",
    hs: "Haskell",
    lhs: "Haskell",
    js: "JavaScript",
    ts: "JavaScript",
    jsx: "JavaScript",
    tsx: "JavaScript",
    mjs: "JavaScript",
    html: "HTML",
    css: "CSS",
} as const;

export const SYNTAX: SyntaxConstants = {
    pre2017: {
        headerMadeBy: "Made by ",
        headerLogin: "Login   ",
        headerLoginBeg: "<",
        headerLoginMid: "",
        headerLoginEnd: ">",
        headerStarted: "Started on  ",
        headerLast: "Last update ",
        headerFor: " for ",
        headerIn: " in ",
        domaineName: "",
        offsetHeaderFile: 13,
        preProcessorStyle: "# ",
    },
    post2017: {
        offsetHeaderFile: 10,
        preProcessorStyle: "#",
    },
    commentStart: {
        Assembly: ";;",
        C: "/*",
        "C++": "/*",
        Makefile: "##",
        Python: "##",
        Shell: "##",
        LaTeX: "%%",
        Java: "/*",
        "C#": "/*",
        ObjectiveC: "/*",
        Rust: "//",
        Haskell: "{-",
        Go: "//",
        JavaScript: "/*",
        HTML: "<!--",
        CSS: "/*",
    },
    commentMid: {
        Assembly: ";;",
        C: "**",
        "C++": "**",
        Makefile: "##",
        Python: "##",
        Shell: "##",
        LaTeX: "%%",
        Java: "**",
        "C#": "**",
        ObjectiveC: "**",
        Rust: "//",
        Haskell: "--",
        Go: "//",
        JavaScript: "**",
        HTML: "----",
        CSS: "**",
    },
    commentEnd: {
        Assembly: ";;",
        C: "*/",
        "C++": "*/",
        Makefile: "##",
        Python: "##",
        Shell: "##",
        LaTeX: "%%",
        Java: "*/",
        "C#": "*/",
        ObjectiveC: "*/",
        Rust: "//",
        Haskell: "-}",
        Go: "//",
        JavaScript: "*/",
        HTML: "--->",
        CSS: "*/",
    },
};

export const DAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
export const MONTHS = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
];
